### ISSUE TITLE
请问，我使用java api在windows上使用qconf报错

### ISSUE THREAD

**Issue by qindongliang** [Qihoo360/QConf#44]
`Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\libqconf_java535428319837713874.so: %1 不是有效的 Win32 应用程序。
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at net.qihoo.qconf.Qconf.loadLib(Unknown Source)
    at net.qihoo.qconf.Qconf.<clinit>(Unknown Source)
    at qconf.Test.main(Test.java:13)
`

请问，你们遇到过这种情况吗，我linux是64位的，jdk都是64位的，win7也是64位的，为什么会报一个32位的错误呢？

**Comment by CatKang** [comment]
qconf没有做对windows的兼容，可以参考：http://blog.csdn.net/i_saw_you/article/details/50749591
